{% set name = "labrps" %}
{% set version = "0.1.pre" %}
{% set build_number = 142 %}
{% set build_number = build_number + 500 %}  # [FEATURE_DEBUG]

package:
    name: {{ name }}
    version: {{ version }}

source:
    # JZ - For local building this is the setup. 
    path: ../
    #git_url: https://github.com/LabRPS/LabRPS
    #git_tag: master
    patches:
        - windows_python_interface.patch


build:
    number: {{ build_number }}
    skip: true  # [py < 38]

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        - {{ cdt('mesa-libegl-devel') }}     # [linux]
        - {{ cdt('libselinux') }}            # [linux]
        - {{ cdt('libxdamage') }}            # [linux]
        - {{ cdt('libxfixes') }}             # [linux]
        - {{ cdt('libxxf86vm') }}            # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('libxi-devel') }}           # [linux]
        - cmake
        - ninja
        - git
    host:
        - boost-cpp
        - python
        - qt
        - xerces-c
        - zlib
        - swig
        - eigen
        - pybind11
        - pivy
        - pyside2
        - doxygen
        - hdf5
        - xorg-libxt  # [linux]
        - freetype
        - libspnav  # [linux]
        - six
        - ply
        - tbb-devel
    run:
        - {{ pin_compatible("pyside2") }}
        - qt
        - xerces-c
        - zlib
        - boost-cpp
        - hdf5
        - python
        - pivy
        - xorg-libxt  # [linux]
        - freetype
        - numpy
        - six
        - pyyaml
        - libspnav  # [linux]
        - ply
    run_constrained:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

#test:
#    commands:
#        - LabRPSCmd -t 0

about:
    home: https://www.labrps.com/
    license: LGPL2.1
    license_family: LGPL
    license_file: LICENSE
    summary: 'LabRPS is a computer tool for the numerical simulation of random phenomenon.'
    description: |
        aims to be a tool for the numerical simulation of random phenomena such as stochastic wind velocity, seismic ground motion, sea surface ... etc.
    doc_url: https://www.wiki.labrps/Main_Page
    dev_url: https://github.com/LabRPS/LabRPS

extra:
    recipe-maintainers:
        - looooo
