#ifndef LABRPS_GEOMETRY_HPP_WORKAROUND
#define LABRPS_GEOMETRY_HPP_WORKAROUND

// Workaround for boost >= 1.74
#define BOOST_ALLOW_DEPRECATED_HEADERS
#include <boost/geometry.hpp>
#undef BOOST_ALLOW_DEPRECATED_HEADERS

#endif // #ifndef LABRPS_GEOMETRY_HPP_WORKAROUND
